version: "3"

vars:
  APP_NAME: calendar-reg-main-api
  BUILD_DIR: ./bin
  MAIN: ./cmd/api/main.go

dotenv: [".env"]

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  # ---------- Development ----------

  dev:
    desc: Run with hot-reload (requires air)
    cmds:
      - air
    preconditions:
      - sh: command -v air
        msg: "air not found. Install: go install github.com/air-verse/air@latest"

  run:
    desc: Run the application
    cmds:
      - go run {{.MAIN}}

  # ---------- Build ----------

  build:
    desc: Build binary
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.APP_NAME}} {{.MAIN}}
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  # ---------- Dependencies ----------

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  # ---------- Quality ----------

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...
    preconditions:
      - sh: command -v golangci-lint
        msg: "golangci-lint not found. Install: https://golangci-lint.run/welcome/install/"

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report → coverage.html"

  check:
    desc: Run fmt + vet + test
    cmds:
      - task: fmt
      - task: vet
      - task: test

  # ---------- Docker ----------

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.APP_NAME}}:latest .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm -p 8080:8080 --env-file .env {{.APP_NAME}}:latest

  # ---------- Tools ----------

  tools:
    desc: Install development tools
    cmds:
      - go install github.com/air-verse/air@latest
      - echo "Tools installed ✓"
