version: "3"

vars:
  APP_NAME: calendar-reg-main-api
  BUILD_DIR: ./bin
  MAIN: ./cmd/api/main.go

dotenv: [".env"]

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  # ---------- Development ----------

  dev:
    desc: Run with hot-reload (requires air)
    cmds:
      - task: swagger
      - air
    preconditions:
      - sh: command -v air
        msg: "air not found. Install: go install github.com/air-verse/air@latest"

  run:
    desc: Run the application
    cmds:
      - go run {{.MAIN}}

  # ---------- Build ----------

  build:
    desc: Build binary
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.APP_NAME}} {{.MAIN}}
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  # ---------- Dependencies ----------

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  # ---------- Quality ----------

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...
    preconditions:
      - sh: command -v golangci-lint
        msg: "golangci-lint not found. Install: https://golangci-lint.run/welcome/install/"

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report → coverage.html"

  check:
    desc: Run fmt + vet + test
    cmds:
      - task: fmt
      - task: vet
      - task: test

  # ---------- Docker ----------

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.APP_NAME}}:latest .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm -p 8080:8080 --env-file .env {{.APP_NAME}}:latest

  # ---------- Swagger ----------

  swagger:
    desc: Generate Swagger docs
    cmds:
      - $(go env GOPATH)/bin/swag init -g {{.MAIN}} -o ./docs
    preconditions:
      - sh: test -f $(go env GOPATH)/bin/swag
        msg: "swag not found. Install: go install github.com/swaggo/swag/cmd/swag@latest"

  # ---------- Proto ----------

  proto:gen:
    desc: Generate Go code from .proto files
    cmds:
      - >-
        protoc
        --go_out=proto/gen/coursepb --go_opt=paths=source_relative
        --go-grpc_out=proto/gen/coursepb --go-grpc_opt=paths=source_relative
        --proto_path=proto
        proto/course_service.proto
    preconditions:
      - sh: command -v protoc
        msg: "protoc not found. Install: brew install protobuf"
      - sh: command -v protoc-gen-go
        msg: "protoc-gen-go not found. Install: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
      - sh: command -v protoc-gen-go-grpc
        msg: "protoc-gen-go-grpc not found. Install: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"

  # ---------- Mock Servers ----------

  mock:grpc:
    desc: Run mock gRPC course server on :50051
    cmds:
      - go run scripts/mock_course_grpc/main.go

  # ---------- Tools ----------

  tools:
    desc: Install development tools
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - echo "Tools installed ✓"

  # ---------- Docker ----------
  docker:build:
    desc: Build docker image
    cmds:
      - docker build -t ghcr.io/cpnext-hub/{{.APP_NAME}}:latest .

  docker:push:
    desc: Push docker image to registry
    cmds:
      - docker push ghcr.io/cpnext-hub/{{.APP_NAME}}:latest
